### PR TITLE
adds README.md to root

### PR DESCRIPTION
**Pull request by tesar-tech**

### CODE REVIEW

**Comment by paulgevers** [comment]
Hi,
Thanks for contributing to WinFF. However, I would be slightly more comfortable if you based your README.md on the winff/README.txt and expend it. E.g. your license claim is not totally aligned with the text there.

**Comment by tesar-tech** [comment]
Its done. Copyright year is changed to 2020. License is from winff/readme.txt (original version was from  winff-windows-packaging/readme.txt)

**Comment by paulgevers** [comment]
@tesar-tech did you push your changes?

**Comment by tesar-tech** [comment]
🤦

**Pull request merged**
