### PR TITLE
WinFF.pt_BR.odt File New

### PR DESCRIPTION
**Pull request by marcelocripe**
Please accept the Brazilian Portuguese language translation of the WinFF program manual.

The file that has the latest translation can also be found at this URL:

https://github.com/marcelocripe/WinFF_pt_BR

I appreciate you not abandoning WinFF.

Thank you very much.

marcelocripe
(Original text in Brazilian Portuguese language)

- - - - -

Por favor, aceite a tradução do idioma o Português do Brasil do manual do programa WinFF.

O arquivo que possui a tradução mais recente também pode ser encontrado neste URL:

https://github.com/marcelocripe/WinFF_pt_BR

Eu agradeço por você não abandonar o WinFF.

Muito obrigado.

marcelocripe
(Texto original em idioma Português do Brasil)

[WinFF.pt_BR.odt](https://github.com/WinFF/winff/files/10933496/WinFF.pt_BR.odt)

### CODE REVIEW

**Comment by paulgevers** [comment]
@marcelocripe: updating the translation is fine, but this MR deleted everything except for the translation, so it can't be merged like it is now.

**Comment by marcelocripe** [comment]
>updating the translation is fine, but this MR deleted everything except for the >translation, so it can't be merged like it is now.

Sorry about that, it wasn't my intention.

The https://github.com/WinFF/winff/tree/master/winff/docs page is blocked and does not accept receiving new files. If you change the permissions, maybe I can send the ".odt" file on the correct page.

I made the file available on this page https://github.com/WinFF/winff/issues/252, but after 6 months the file was not added on the page https://github.com/WinFF/winff/tree/master/winff /docs.

Please add the file on https://github.com/WinFF/winff/tree/master/winff/docs page by me. It will be for the good of the many Brazilian WinFF users.

Grateful.

- - - - -

>updating the translation is fine, but this MR deleted everything except for the >translation, so it can't be merged like it is now.

Desculpe-me por isso, não era a minha intenção.

A página https://github.com/WinFF/winff/tree/master/winff/docs está bloqueada e não aceita receber novos arquivos. Se você alterar as permissões, tavez eu consiga enviar na página correta o arquivo ".odt".

Eu disponibilizei o arquivo nesta página https://github.com/WinFF/winff/issues/252, mas após 6 meses o arquivo não foi adicionado na página https://github.com/WinFF/winff/tree/master/winff/docs.

Por favor, adicione o arquivo na página https://github.com/WinFF/winff/tree/master/winff/docs por mim. Será para o bem dos vários usuários Brasileiros do WinFF.

Grato.

**Comment by paulgevers** [comment]
Pushed. Thanks

**Comment by marcelocripe** [comment]
Thank you very much.

**Comment by marcelocripe** [comment]
Please, [paulgevers](https://github.com/paulgevers) and [PeterBBBBB](https://github.com/PeterBBBBB) could you update the WinFF.pt_BR.odt file?

I've revised WinFF.pt_BR.odt, made some corrections (due to some typos) and improvements to the explanatory phrases, and I hope the latest file will be even more useful than the old one for new WinFF users.

I produced the video https://youtu.be/HuaKjjvSpDs demonstrating how to convert a video file to audio with WinFF from antiX Linux through the YouTube channel called "antiX Linux em Português".

Thank you very much for keeping WinFF updated.

- - - - -

Por favor, [paulgevers](https://github.com/paulgevers) e [PeterBBBBB](https://github.com/PeterBBBBB), vocês poderiam atualizar o arquivo WinFF.pt_BR.odt?

Eu revisei o WinFF.pt_BR.odt, realizei algumas correções (devido alguns erros de digitação) e melhorias nas frases explicativas e espero que o arquivo mais recente possa ser ainda mais útil do que o arquivo antigo para os novos usuários do WinFF.

Eu produzi o vídeo https://youtu.be/HuaKjjvSpDs demonstrando como converter um arquivo de vídeo para áudio com o WinFF a partir do antiX Linux por meio do canal do YouTube chamado de "antiX Linux em Português".

Muito obrigado por manter o WinFF atualizado.

[WinFF.pt_BR.odt](https://github.com/user-attachments/files/24963987/WinFF.pt_BR.odt)

**Comment by paulgevers** [comment]
@marcelocripe; can you please create a new PR for the changes you want?

**Comment by marcelocripe** [comment]
Hello [paulgevers](https://github.com/paulgevers).

> can you please create a new PR for the changes you want?

I tried to send the new file, but I received the message:

"Uploads are disabled.

File uploads require push access to this repository."

What I managed to do was https://github.com/WinFF/winff/pull/260 and I'm not sure if I did it correctly when requesting the deletion of the old file.

**Pull request closed without merging**
